#spring.application.name=open
spring:
  application:
    name: open

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4317
  metrics:
    exporter: otlp
  traces:
    exporter: otlp

management:
  metrics:
    export:
      otlp:
        enabled: true
        endpoint: http://localhost:4317
        step: 10s
#        ?? ??? ????? ?? ?? 10 ????? ???????? ?? ???? OTLP ?? ???? ??? ????? ?????:
#otel:
#  exporter:
#    otlp:
#      endpoint: http://localhost:4317
